/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KarunnyiAmbulanceWlList {
    }
}
declare global {
    interface HTMLKarunnyiAmbulanceWlListElement extends Components.KarunnyiAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLKarunnyiAmbulanceWlListElement: {
        prototype: HTMLKarunnyiAmbulanceWlListElement;
        new (): HTMLKarunnyiAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "karunnyi-ambulance-wl-list": HTMLKarunnyiAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface KarunnyiAmbulanceWlList {
    }
    interface IntrinsicElements {
        "karunnyi-ambulance-wl-list": KarunnyiAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "karunnyi-ambulance-wl-list": LocalJSX.KarunnyiAmbulanceWlList & JSXBase.HTMLAttributes<HTMLKarunnyiAmbulanceWlListElement>;
        }
    }
}
